import React, { useState, useRef, useEffect } from 'react';
import { 
  Sparkles, 
  RotateCcw, 
  Volume2, 
  VolumeX, 
  Copy, 
  Check, 
  Send, 
  Loader2,
  ArrowUpRight,
  ExternalLink,
  Layers,
  Sliders
} from 'lucide-react';
import { askShidneyAI } from '../services/shidneyAiService';

export default function ShidneyAIChat({
  currentUser,
  selectedBank,
  activePolicy,
  selectedProduct,
  policies = {},
  onSelectPolicy,
  onSelectProduct,
  onSwitchToRequestMode,
  onQuickToggleUserRole,
  onOpenEditModal,
  onOpenExportModal,
}) {
  const userName = currentUser?.name?.split(' ')[0] || 'David';

  const [messages, setMessages] = useState([
    {
      id: 'welcome-1',
      sender: 'assistant',
      time: 'Just now',
      text: `Hi ${userName}! How can I help you today?`,
    }
  ]);

  const [inputPrompt, setInputPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [copiedId, setCopiedId] = useState(null);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [speakingMsgId, setSpeakingMsgId] = useState(null);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  // Handle clickable action links generated by Shidney
  const handleActionClick = (actionUrl) => {
    if (!actionUrl) return;

    if (actionUrl.startsWith('action:policy:')) {
      const policyId = actionUrl.replace('action:policy:', '').trim();
      if (onSelectPolicy) onSelectPolicy(policyId);
      const targetPolicy = policies[policyId];
      if (targetPolicy?.applicableProducts?.[0] && onSelectProduct) {
        onSelectProduct(targetPolicy.applicableProducts[0]);
      }
    } else if (actionUrl.startsWith('action:product:')) {
      const productId = actionUrl.replace('action:product:', '').trim();
      if (onSelectProduct) onSelectProduct(productId);
      const matchingPolicy = Object.values(policies).find(p => (p.applicableProducts || []).includes(productId));
      if (matchingPolicy && onSelectPolicy) {
        onSelectPolicy(matchingPolicy.id);
      }
    } else if (actionUrl === 'action:modal:edit-spec') {
      if (onOpenEditModal) onOpenEditModal();
    } else if (actionUrl === 'action:modal:export-cert') {
      if (onOpenExportModal) onOpenExportModal();
    } else if (actionUrl === 'action:feed:request-change') {
      if (onSwitchToRequestMode) onSwitchToRequestMode();
    } else if (actionUrl === 'action:role:toggle') {
      if (onQuickToggleUserRole) onQuickToggleUserRole();
    } else if (actionUrl.startsWith('http://') || actionUrl.startsWith('https://')) {
      window.open(actionUrl, '_blank', 'noopener,noreferrer');
    }
  };

  // Handle Speech Synthesis Read-Aloud
  const handleToggleSpeech = (msgId, text) => {
    if (!('speechSynthesis' in window)) return;

    if (isSpeaking && speakingMsgId === msgId) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      setSpeakingMsgId(null);
      return;
    }

    window.speechSynthesis.cancel();
    const cleanText = text
      .replace(/###|\*\*|\*|`|\[.*?\]\(.*?\)/g, '')
      .replace(/#+/g, '')
      .trim();

    const utterance = new SpeechSynthesisUtterance(cleanText);
    utterance.rate = 1.05;
    utterance.pitch = 1.0;
    utterance.onend = () => {
      setIsSpeaking(false);
      setSpeakingMsgId(null);
    };
    utterance.onerror = () => {
      setIsSpeaking(false);
      setSpeakingMsgId(null);
    };

    window.speechSynthesis.speak(utterance);
    setIsSpeaking(true);
    setSpeakingMsgId(msgId);
  };

  // Copy message text to clipboard
  const handleCopyText = (msgId, text) => {
    navigator.clipboard.writeText(text);
    setCopiedId(msgId);
    setTimeout(() => setCopiedId(null), 2000);
  };

  // Clear chat history / Start new conversation
  const handleStartNewConvo = () => {
    if (window.speechSynthesis) window.speechSynthesis.cancel();
    setIsSpeaking(false);
    setMessages([
      {
        id: `welcome-${Date.now()}`,
        sender: 'assistant',
        time: 'Just now',
        text: `Hi ${userName}! How can I help you today?`,
      }
    ]);
  };

  // Handle submitting user message
  const handleSendMessage = async (textToSend) => {
    const text = (textToSend || inputPrompt).trim();
    if (!text || isLoading) return;

    const userMsg = {
      id: `u-${Date.now()}`,
      sender: 'user',
      time: 'Just now',
      text: text,
    };

    setMessages(prev => [...prev, userMsg]);
    setInputPrompt('');
    setIsLoading(true);

    try {
      const response = await askShidneyAI({
        prompt: text,
        conversationHistory: messages,
        context: {
          currentUser,
          selectedBank,
          activePolicy,
          selectedProduct,
          policies,
        },
      });

      const aiMsg = {
        id: `ai-${Date.now()}`,
        sender: 'assistant',
        time: 'Just now',
        text: response.text,
      };

      setMessages(prev => [...prev, aiMsg]);
    } catch (err) {
      console.error('Error fetching Shidney response:', err);
      setMessages(prev => [
        ...prev,
        {
          id: `ai-err-${Date.now()}`,
          sender: 'assistant',
          time: 'Just now',
          text: `I'm here to help with questions about Australian banking standards, Personal Loan assessment rules (APRA APS 220), or navigating the platform for ${selectedBank?.name || 'CBA'}. What would you like to explore?`,
        }
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  // Render markdown-like formatting cleanly
  const renderFormattedText = (text) => {
    const lines = text.split('\n');
    return lines.map((line, idx) => {
      // Headings
      if (line.startsWith('### ')) {
        return (
          <h4 key={idx} className="font-bold text-slate-900 text-[12px] mt-2 mb-1 text-blue-900">
            {line.replace('### ', '')}
          </h4>
        );
      }
      if (line.startsWith('## ')) {
        return (
          <h3 key={idx} className="font-bold text-slate-900 text-xs mt-2 mb-1">
            {line.replace('## ', '')}
          </h3>
        );
      }

      // Bullet points
      if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
        const bulletText = line.trim().substring(2);
        return (
          <div key={idx} className="flex items-start gap-1.5 pl-1 my-0.5 text-slate-700 text-[11.5px] leading-relaxed">
            <span className="text-blue-600 font-bold">•</span>
            <span>{parseInlineMarkdown(bulletText)}</span>
          </div>
        );
      }

      // Numbered lists
      if (/^\d+\.\s/.test(line.trim())) {
        const num = line.trim().match(/^\d+\./)[0];
        const rest = line.trim().replace(/^\d+\.\s*/, '');
        return (
          <div key={idx} className="flex items-start gap-1.5 pl-1 my-0.5 text-slate-700 text-[11.5px] leading-relaxed">
            <span className="font-bold text-blue-800 text-[11px] min-w-[16px]">{num}</span>
            <span>{parseInlineMarkdown(rest)}</span>
          </div>
        );
      }

      // Empty line
      if (!line.trim()) {
        return <div key={idx} className="h-1" />;
      }

      // Regular text
      return (
        <p key={idx} className="text-slate-700 text-[11.5px] leading-relaxed my-0.5">
          {parseInlineMarkdown(line)}
        </p>
      );
    });
  };

  // Parse inline [links](action:...), **bold**, and `code` tags
  const parseInlineMarkdown = (str) => {
    const parts = [];
    const regex = /(\[.*?\]\(.*?\)|\*\*.*?\*\*|`.*?`)/g;
    let lastIdx = 0;
    let match;

    while ((match = regex.exec(str)) !== null) {
      if (match.index > lastIdx) {
        parts.push(str.substring(lastIdx, match.index));
      }
      const token = match[0];
      
      if (token.startsWith('[') && token.includes('](')) {
        const closeBracketIdx = token.indexOf('](');
        const linkText = token.substring(1, closeBracketIdx);
        const linkUrl = token.substring(closeBracketIdx + 2, token.length - 1);

        parts.push(
          <button
            key={match.index}
            type="button"
            onClick={() => handleActionClick(linkUrl)}
            className="inline-flex items-center gap-1 bg-blue-50 hover:bg-blue-100 active:bg-blue-200 text-blue-700 hover:text-blue-900 border border-blue-200 hover:border-blue-400 px-2 py-0.5 rounded-md font-bold text-[11px] transition cursor-pointer mx-0.5 my-0.5 shadow-2xs group"
          >
            <Sparkles className="w-3 h-3 text-blue-600 group-hover:scale-110 transition" />
            <span>{linkText}</span>
            <ArrowUpRight className="w-3 h-3 text-blue-500 group-hover:translate-x-0.5 transition" />
          </button>
        );
      } else if (token.startsWith('**') && token.endsWith('**')) {
        parts.push(
          <strong key={match.index} className="font-bold text-slate-900">
            {token.substring(2, token.length - 2)}
          </strong>
        );
      } else if (token.startsWith('`') && token.endsWith('`')) {
        parts.push(
          <code key={match.index} className="bg-slate-100 text-blue-900 px-1 py-0.2 rounded font-mono text-[10.5px] border border-slate-200">
            {token.substring(1, token.length - 1)}
          </code>
        );
      }
      lastIdx = regex.lastIndex;
    }

    if (lastIdx < str.length) {
      parts.push(str.substring(lastIdx));
    }

    return parts.length > 0 ? parts : str;
  };

  return (
    <div className="flex flex-col h-full bg-slate-50/40">
      {/* Messages Scroll Area */}
      <div className="flex-1 overflow-y-auto custom-scrollbar p-3 space-y-3">
        {messages.map((msg) => {
          const isUser = msg.sender === 'user';

          if (isUser) {
            return (
              <div key={msg.id} className="flex items-start justify-end gap-2 pl-6">
                <div className="bg-slate-900 text-white rounded-2xl rounded-tr-xs px-3 py-2 text-xs shadow-2xs max-w-[90%] space-y-1">
                  <div className="text-[11.5px] leading-relaxed">{msg.text}</div>
                  <div className="text-[9.5px] text-slate-400 text-right">{msg.time}</div>
                </div>
                <div className="w-6 h-6 rounded-full bg-blue-600 text-white font-bold text-[10px] flex items-center justify-center flex-shrink-0 shadow-2xs">
                  {currentUser?.avatar || 'DM'}
                </div>
              </div>
            );
          }

          // Shidney Assistant Message
          return (
            <div key={msg.id} className="flex items-start gap-2 pr-2">
              <div className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center flex-shrink-0 shadow-2xs mt-0.5">
                <Sparkles className="w-3.5 h-3.5 text-white" />
              </div>

              <div className="flex-1 bg-white border border-slate-200/90 rounded-2xl rounded-tl-xs p-3 shadow-2xs space-y-1.5 text-xs">
                {/* Message Header */}
                <div className="flex items-center justify-between border-b border-slate-100 pb-1 text-[10.5px]">
                  <span className="font-bold text-slate-900 flex items-center gap-1">
                    <span>Shidney</span>
                    <span className="text-[9px] font-normal text-slate-400">• {msg.time}</span>
                  </span>

                  <div className="flex items-center gap-1">
                    <button
                      onClick={() => handleToggleSpeech(msg.id, msg.text)}
                      title={isSpeaking && speakingMsgId === msg.id ? "Stop voice" : "Read aloud"}
                      className="p-0.5 rounded text-slate-400 hover:text-blue-700 hover:bg-slate-100 transition cursor-pointer"
                    >
                      {isSpeaking && speakingMsgId === msg.id ? (
                        <VolumeX className="w-3.5 h-3.5 text-rose-600" />
                      ) : (
                        <Volume2 className="w-3.5 h-3.5" />
                      )}
                    </button>
                    <button
                      onClick={() => handleCopyText(msg.id, msg.text)}
                      title="Copy response"
                      className="p-0.5 rounded text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition cursor-pointer"
                    >
                      {copiedId === msg.id ? (
                        <Check className="w-3.5 h-3.5 text-emerald-600" />
                      ) : (
                        <Copy className="w-3.5 h-3.5" />
                      )}
                    </button>
                  </div>
                </div>

                {/* Natural Formatted Content */}
                <div className="space-y-1">
                  {renderFormattedText(msg.text)}
                </div>
              </div>
            </div>
          );
        })}

        {/* Loading Indicator */}
        {isLoading && (
          <div className="flex items-center gap-2 pl-1 animate-in fade-in duration-200">
            <div className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center flex-shrink-0 shadow-2xs">
              <Sparkles className="w-3.5 h-3.5 animate-spin" />
            </div>
            <div className="bg-white border border-blue-200 rounded-2xl rounded-tl-xs px-3 py-2 shadow-2xs flex items-center gap-2 text-[11px] text-blue-900 font-medium">
              <Loader2 className="w-3.5 h-3.5 text-blue-600 animate-spin" />
              <span>Shidney is typing...</span>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Bottom AI Prompt Input Form with Clean New Chat Button */}
      <div className="p-2.5 bg-white border-t border-slate-200">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSendMessage();
          }}
          className="flex items-center gap-1.5"
        >
          {/* Subtle New Conversation Button */}
          <button
            type="button"
            onClick={handleStartNewConvo}
            title="Start new conversation"
            className="p-2 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-100 border border-slate-200 transition cursor-pointer flex items-center justify-center flex-shrink-0"
          >
            <RotateCcw className="w-3.5 h-3.5" />
          </button>

          <div className="relative flex-1">
            <input
              type="text"
              value={inputPrompt}
              onChange={(e) => setInputPrompt(e.target.value)}
              placeholder="Ask Shidney anything..."
              disabled={isLoading}
              className="w-full bg-slate-50 border border-slate-200 focus:bg-white focus:border-blue-500 rounded-xl pl-3 pr-8 py-2 text-xs text-slate-900 placeholder-slate-400 outline-none transition"
            />
            {inputPrompt && (
              <button
                type="button"
                onClick={() => setInputPrompt('')}
                className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 text-xs cursor-pointer"
              >
                ✕
              </button>
            )}
          </div>

          <button
            type="submit"
            disabled={!inputPrompt.trim() || isLoading}
            className="bg-blue-600 hover:bg-blue-700 disabled:opacity-40 text-white p-2 rounded-xl text-xs font-bold transition cursor-pointer flex items-center justify-center flex-shrink-0 shadow-2xs"
            title="Send message"
          >
            <Send className="w-3.5 h-3.5" />
          </button>
        </form>
      </div>
    </div>
  );
}
